[package]
name = "task-batch"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "blocking"] } # HTTPクライアント
serde = { version = "1.0", features = ["derive"] } # シリアライズ/デシリアライズ
serde_json = "1.0" # JSON扱い
dotenv = "0.15" # .envファイル読み込み
anyhow = "1.0" # エラーハンドリング
serde_yaml = "0.9"
base64 = "0.21"
chrono = { version = "0.4", features = ["serde"] }
regex = "1"
